CREATE TABLE tasks (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(60) NOT NULL,
	description VARCHAR(200) NULL,
	done BOOLEAN NOT NULL DEFAULT 0,
	createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);